name: Exploring Variables and SEcrets

on: push

# ENV @ the step level
# jobs:
#     docker:
#         runs-on: ubuntu-latest
#         steps:
#             - name: Docker Build
#               env: 
#                 CONTAINTER_REGISTRY: docker.io
#                 DOCKER_USERNAME: arolsmith
#                 IMAGE_NAME: github-actions-nginx
#               run: echo docker build -t ${{ env.CONTAINTER_REGISTRY }}/$DOCKER_USERNAME/$IMAGE_NAME:latest

#             - name: Docker Login
#               env: 
#                 DOCKER_PASSWORD: xxxxxxxxx
#                 DOCKER_USERNAME: xxxxxxxxxxxxx   
#               run: docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD
#             - name: Docker Publish
#               env:
#                 CONTAINER_REGISTRY: docker.io
#                 DOCKER_USERNAME: xxxxxxxxx
#                 IMAGE_NAME: github-actions-nginx
#               run: docker push docker.io/dockerUsername/imageName:latest
             
              

    # deploy:
    #     needs: docker
    #     runs-on: ubuntu-latest
    #     steps:
    #       - name: Docker
    #         run: docker run -d -p 8080:80 docker.io/dockerUsername/imageName:latest


# ENV at job level           
# jobs:
#   docker:
#     env: 
#       CONTAINTER_REGISTRY: docker.io
#       DOCKER_USERNAME: arolsmith
#       IMAGE_NAME: github-actions-nginx
#     runs-on: ubuntu-latest
#     steps:
#         - name: Docker Build

#           run: echo docker build -t ${{ env.CONTAINTER_REGISTRY }}/$DOCKER_USERNAME/$IMAGE_NAME:latest

#         - name: Docker Login
#           env: 
#             DOCKER_PASSWORD: xxxxxxxxx
#             DOCKER_USERNAME: xxxxxxxxxxxxx   
#           run: docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD
#         - name: Docker Publish
#           env:
#             CONTAINER_REGISTRY: docker.io
#             DOCKER_USERNAME: xxxxxxxxx
#             IMAGE_NAME: github-actions-nginx
#           run: docker push docker.io/dockerUsername/imageName:latest
            

#   deploy:
#       needs: docker
#       runs-on: ubuntu-latest
#       steps:
#         - name: Docker
#           run: docker run -d -p 8080:80 docker.io/dockerUsername/imageName:latest

# ENV at workflow level

env: 
  CONTAINTER_REGISTRY: docker.io
  DOCKER_USERNAME: arolsmith
  IMAGE_NAME: github-actions-nginx
  
jobs:
  docker:

    runs-on: ubuntu-latest
    steps:
        - name: Docker Build

          run: echo docker build -t ${{ env.CONTAINTER_REGISTRY }}/$DOCKER_USERNAME/$IMAGE_NAME:latest

        - name: Docker Login
          env: 
            DOCKER_PASSWORD: xxxxxxxxx
            DOCKER_USERNAME: xxxxxxxxxxxxx   
          run: docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD
        - name: Docker Publish
          env:
            CONTAINER_REGISTRY: docker.io
            DOCKER_USERNAME: xxxxxxxxx
            IMAGE_NAME: github-actions-nginx
          run: docker push docker.io/dockerUsername/imageName:latest
            

  deploy:
      needs: docker
      runs-on: ubuntu-latest
      steps:
        - name: Docker
          run: docker run -d -p 8080:80 docker.io/dockerUsername/imageName:latest